# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axhub < Formula
  desc "CLI for the axhub developer platform"
  homepage "https://github.com/jocoding-ax-partners/ax-hub-cli"
  version "0.0.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jocoding-ax-partners/ax-hub-cli/releases/download/v0.0.1/axhub_0.0.1_darwin_amd64.tar.gz"
      sha256 "03ffe759d3fca076022a28d2155187e0cee0f0e79fe80f765e3b941ff607d5fc"

      define_method(:install) do
        bin.install "axhub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jocoding-ax-partners/ax-hub-cli/releases/download/v0.0.1/axhub_0.0.1_darwin_arm64.tar.gz"
      sha256 "671983ee54fc548c397a5f7f0e5a89121a4500691a2bdeef7c1203ecdb85ca6b"

      define_method(:install) do
        bin.install "axhub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jocoding-ax-partners/ax-hub-cli/releases/download/v0.0.1/axhub_0.0.1_linux_amd64.tar.gz"
      sha256 "7d6fe79af9c9f9be9ca1507fb420b6e70d56420735f4d82c6d70ade3037788bc"
      define_method(:install) do
        bin.install "axhub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jocoding-ax-partners/ax-hub-cli/releases/download/v0.0.1/axhub_0.0.1_linux_arm64.tar.gz"
      sha256 "38fec2d89820b5007ae854f7e56626170a41e9872faec9ea047f7004250d0d89"
      define_method(:install) do
        bin.install "axhub"
      end
    end
  end

  test do
    system "#{bin}/axhub", "--version"
  end
end
