# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axhub < Formula
  desc "CLI for the axhub developer platform"
  homepage "https://github.com/jocoding-ax-partners/ax-hub-cli"
  version "0.1.8"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cli.jocodingax.ai/0.1.8/axhub_0.1.8_darwin_amd64.tar.gz"
      sha256 "8450cbd8b3fb9a8e551b4fbf334c3d8227646b2dc93978f0bde3cd3875fb678d"

      define_method(:install) do
        bin.install "axhub"
      end
    end
    if Hardware::CPU.arm?
      url "https://cli.jocodingax.ai/0.1.8/axhub_0.1.8_darwin_arm64.tar.gz"
      sha256 "d9c661090687e2c9fb191dbd8e8802f73586f4b85d4fcaf2f191185ff59090b4"

      define_method(:install) do
        bin.install "axhub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cli.jocodingax.ai/0.1.8/axhub_0.1.8_linux_amd64.tar.gz"
      sha256 "06b084a24ebd46791eb155f4f98799437a8d268248ffcea19fff5f475b499d50"
      define_method(:install) do
        bin.install "axhub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cli.jocodingax.ai/0.1.8/axhub_0.1.8_linux_arm64.tar.gz"
      sha256 "6a1ca460decaca6de804df9f7c63fde2792dc36aac5946f266ca974f4256c63d"
      define_method(:install) do
        bin.install "axhub"
      end
    end
  end

  test do
    system bin/"axhub", "--version"
  end
end
