# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axhub < Formula
  desc "CLI for the axhub developer platform"
  homepage "https://github.com/jocoding-ax-partners/ax-hub-cli"
  version "0.0.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jocoding-ax-partners/ax-hub-cli/releases/download/v0.0.1/axhub_0.0.1_darwin_amd64.tar.gz"
      sha256 "cb7709eb414b786c51cd66ac04faebf705aee921fa871f869e204a8b9148478e"

      define_method(:install) do
        bin.install "axhub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jocoding-ax-partners/ax-hub-cli/releases/download/v0.0.1/axhub_0.0.1_darwin_arm64.tar.gz"
      sha256 "f11e2130e6380302ffdc9a590501540871a266f424a754fa66f706db58c9e91a"

      define_method(:install) do
        bin.install "axhub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jocoding-ax-partners/ax-hub-cli/releases/download/v0.0.1/axhub_0.0.1_linux_amd64.tar.gz"
      sha256 "7184a29461e236bc7520614969807953351aff08f7ce1b68c547e62ec60ace02"
      define_method(:install) do
        bin.install "axhub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jocoding-ax-partners/ax-hub-cli/releases/download/v0.0.1/axhub_0.0.1_linux_arm64.tar.gz"
      sha256 "4641adcfde7572045d23538b46db72fe8dce92cf76928a2e82637f97bc06d286"
      define_method(:install) do
        bin.install "axhub"
      end
    end
  end

  test do
    system "#{bin}/axhub", "--version"
  end
end
