# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axhub < Formula
  desc "CLI for the axhub developer platform"
  homepage "https://github.com/jocoding-ax-partners/ax-hub-cli"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cli.jocodingax.ai/0.1.0/axhub_0.1.0_darwin_amd64.tar.gz"
      sha256 "79b06e6641f4f453a68623b6701ff00d3ed9f152ea37730e7137f4c7908eff79"

      define_method(:install) do
        bin.install "axhub"
      end
    end
    if Hardware::CPU.arm?
      url "https://cli.jocodingax.ai/0.1.0/axhub_0.1.0_darwin_arm64.tar.gz"
      sha256 "df9c2e33ddcfe7d5e30ae0a475860ef3299970a62b8f846aaea1693a6ab96beb"

      define_method(:install) do
        bin.install "axhub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cli.jocodingax.ai/0.1.0/axhub_0.1.0_linux_amd64.tar.gz"
      sha256 "0ef1a17dd8f85441c36e155b61df5d7c71bfb7e9650ff79c0f2ad954ae53638d"
      define_method(:install) do
        bin.install "axhub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cli.jocodingax.ai/0.1.0/axhub_0.1.0_linux_arm64.tar.gz"
      sha256 "424363357df34ceacc0072a030f6cfd1463fe70b7a87668fbb1903f7bf5397bc"
      define_method(:install) do
        bin.install "axhub"
      end
    end
  end

  test do
    system bin/"axhub", "--version"
  end
end
